name: Fetch

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */12 * * *'

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch
        run: |
          rm *csv
          for ticker in $(cat watchlist); do
            (
              file="$ticker".csv
              url="https://query1.finance.yahoo.com/v7/finance/download/$ticker?period1=0&period2="$(date +%s)"&interval=1d&events=history"
              curl $url -o $file
              cat $file | cut -d , -f 1,5 > tmp-$file && [ $(wc -l < tmp-$file) -gt 10 ] && mv tmp-$file $file
            ) & 
          done
          wait
      - name: Commit
        run: |
          set -x
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add --all && git commit -m "Add files" && git push --force
          git reset $(git commit-tree HEAD^{tree} -m "Commit")
          git push --force
      - name: Delete workflow runs
        run: |
          gh api -X GET /repos/${{ github.repository }}/actions/runs \
            | jq '.workflow_runs[] | .id' \
            | tail -n +2 \
            | xargs -n1 -I % gh api repos/${{ github.repository }}/actions/runs/% -X DELETE
